---
- name: Run command on remote hosts
  hosts: all
  become: true
 
  vars:
    output_dir: "{{ lookup('env', 'HOME') }}"  # Use the home directory of the Ansible user
 
  tasks:
    - name: Run command
      shell: |
        echo "$(cat /etc/os-release | grep PRETTY_NAME) $(ip -4 addr show | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | paste -s -d' ')"
      with_items: "{{ ansible_play_hosts }}"
      delegate_to: "{{ item }}"
      register: command_output
 
    - name: Append output to file on Ansible control node
      local_action:
        module: lineinfile
        path: "{{ output_dir }}/all.log"
        line: "{{ item.stdout }}"
        create: yes
        state: present
      loop: "{{ command_output.results }}"
      when: item.stdout is defined
