---
- name: Run command on remote hosts
  hosts: all
  become: true

#This was not in the presentation but copies ssh activity from remote boxes.
#It stores the ssh records in seperate text files where Ansible is run. Text files are named with host IP.
#Great to see how often boxes are used as well as during incident response.
  vars:
    command: "sudo grep 'Accepted' /var/log/secure* | awk '{print $0}'"
    output_dir: "/home/ec2-user/reports"

  tasks:
    - name: Run command
      shell: "{{ command }}"
      register: command_output

    - name: Save output to file
      local_action:
        module: copy
        content: "{{ command_output.stdout }}"
        dest: "{{ output_dir }}/{{ inventory_hostname }}.log"
